package hellojpa;

import jakarta.persistence.DiscriminatorColumn;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn
public class Item {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private int price;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    /*
    * JPA는 기본전략이 싱글 테이블로 구성되게 한다.
    * create table Item (
        price integer not null,
        id bigint generated by default as identity,
        DTYPE varchar(31) not null,
        actor varchar(255),
        artist varchar(255),
        author varchar(255),
        director varchar(255),
        isbn varchar(255),
        name varchar(255),
        primary key (id)
    )
    *
    * 조인 전략을 사용하기 위해서는
    * @Inheritance(strategy = InheritanceType.JOINED) 를 추가한다.
    * */

    /*
    * @DiscriminatorColumn을 추가하면 DTYPE이 테이블에 추가된것을 확인할 수 있다.
    * DTYPE은 Entity 이름이 들어간다. -> 운영측면에서 왠만하면 추가하는 편이 좋다.
    *
    * create table Item (
        price integer not null,
        id bigint generated by default as identity,
        DTYPE varchar(31) not null,
        name varchar(255),
        primary key (id)
    )
    *
    * */
}
